import {
  Baby,
  HeartHandshake,
  UserCheck,
  DollarSign,
  Briefcase,
  Globe,
  Shield,
  Activity,
  Users,
  Wine,
  Brain,
  Home,
  Leaf,
  Scale,
  Car,
  type LucideIcon,
} from "lucide-react"

export interface Contactpersoon {
  naam: string
  telefoon?: string
}

export interface Netwerkpartner {
  id: number
  naam: string
  beschrijving: string
  levensgebieden: string[]
  adres?: string | null
  telefoon?: string | null
  email?: string | null
  website?: string | null
  websites?: string[]
  whatsapp?: string | null
  contactpersoon?: string | null
  contactpersonen?: Contactpersoon[]
  tags: string[]
}

export interface Levensgebied {
  name: string
  icon: LucideIcon
  color: string
}

// Metadata over de gemeente
export const gemeenteMeta = {
  gemeente: "Edam-Volendam",
  laatstBijgewerkt: "2026-07-22",
  beschrijving:
    "Netwerkpartijen en organisaties voor de kennisbank netwerkmatcher gemeente Edam-Volendam",
}

// De levensgebieden met bijbehorend icoon en kleur.
export const levensgebieden: Levensgebied[] = [
  { name: "Jeugd & Gezin", icon: Baby, color: "bg-pink-100 text-pink-700" },
  { name: "Zorg & Welzijn", icon: HeartHandshake, color: "bg-red-100 text-red-700" },
  { name: "Ouderenzorg", icon: UserCheck, color: "bg-amber-100 text-amber-700" },
  { name: "Financiën & Schulden", icon: DollarSign, color: "bg-green-100 text-green-700" },
  { name: "Werk & Inkomen", icon: Briefcase, color: "bg-blue-100 text-blue-700" },
  { name: "Inburgering & Participatie", icon: Globe, color: "bg-cyan-100 text-cyan-700" },
  { name: "Veiligheid", icon: Shield, color: "bg-orange-100 text-orange-700" },
  { name: "Gezondheid & Sport", icon: Activity, color: "bg-teal-100 text-teal-700" },
  { name: "Ontmoeting & Sociaal", icon: Users, color: "bg-purple-100 text-purple-700" },
  { name: "Verslavingszorg", icon: Wine, color: "bg-rose-100 text-rose-700" },
  { name: "GGZ & Psychische Hulp", icon: Brain, color: "bg-indigo-100 text-indigo-700" },
  { name: "Wonen", icon: Home, color: "bg-sky-100 text-sky-700" },
  { name: "Duurzaamheid & Energie", icon: Leaf, color: "bg-lime-100 text-lime-700" },
  { name: "Juridisch", icon: Scale, color: "bg-yellow-100 text-yellow-700" },
  { name: "Vervoer", icon: Car, color: "bg-slate-100 text-slate-700" },
]

export const netwerkpartners: Netwerkpartner[] = [
  {
    id: 1,
    naam: "Gemeente Edam-Volendam – Team Jeugd",
    beschrijving:
      "Team binnen de gemeente dat jeugdigen en ouders ondersteunt bij vragen rondom opvoeden, opgroeien en jeugdhulp. Geeft advies, stelt samen met gezinnen een plan op en kan passende specialistische jeugdhulp inzetten.",
    levensgebieden: ["Jeugd & Gezin"],
    adres: "W. van der Knoopdreef 1, 1132 KN Volendam",
    telefoon: "0299 398 398",
    email: null,
    website: "https://www.edam-volendam.nl/jeugdhulp",
    tags: ["jeugd", "jeugdhulp", "kinderen", "jongeren", "ouders", "gezin", "opvoeding", "opvoedondersteuning", "opgroeien", "ontwikkeling", "begeleiding", "ondersteuning", "mentale gezondheid", "veiligheid", "preventie", "participatie", "welzijn"],
  },
  {
    id: 2,
    naam: "Gemeente Edam-Volendam – Team Wmo",
    beschrijving:
      "Ondersteunt inwoners die door ouderdom, een beperking of ziekte hulp nodig hebben om zo lang mogelijk zelfstandig thuis te wonen en actief mee te doen in de samenleving. Behandelt aanvragen voor Wmo-voorzieningen, zoals huishoudelijke ondersteuning, begeleiding, dagbesteding, hulpmiddelen, woningaanpassingen en vervoersvoorzieningen.",
    levensgebieden: ["Zorg & Welzijn", "Ouderenzorg"],
    adres: "W. van der Knoopdreef 1, 1132 KN Volendam",
    telefoon: "0299 398 398",
    email: null,
    website: "https://www.edam-volendam.nl/ondersteuningvoor-ouderen-mensen-met-een-beperking-enandere-hulpbehoevenden-wmo",
    tags: ["Wmo", "maatschappelijke ondersteuning", "zorg", "ondersteuning", "zelfstandig thuis wonen", "langer thuis wonen", "huishoudelijke hulp", "huishoudelijke ondersteuning", "begeleiding", "dagbesteding", "woningaanpassing", "woonvoorzieningen", "rolstoel", "scootmobiel", "vervoersvoorziening", "hulpmiddelen", "mantelzorg", "mantelzorgondersteuning", "zelfredzaamheid", "participatie", "ouderen", "mensen met een beperking"],
  },
  {
    id: 3,
    naam: "Gemeente Edam-Volendam – Breed Sociaal Loket (BSL)",
    beschrijving:
      "Het Breed Sociaal Loket (BSL) is het centrale aanspreekpunt van de gemeente Edam-Volendam voor vragen over zorg, werk, inkomen, schulden, jeugd en ondersteuning. Samen wordt gekeken welke hulp of voorziening het beste past bij de situatie van de inwoner.",
    levensgebieden: ["Zorg & Welzijn", "Financiën & Schulden", "Werk & Inkomen"],
    adres: "W. van der Knoopdreef 1, 1132 KN Volendam",
    telefoon: "0299 398 398",
    email: null,
    website: "https://www.edam-volendam.nl/bsl-online",
    tags: ["zorg", "welzijn", "ondersteuning", "Wmo", "jeugd", "werk", "inkomen", "schulden", "schuldhulpverlening", "geldzaken", "participatie", "inburgering", "mantelzorg", "wonen", "advies", "doorverwijzing", "voorzieningen", "zelfredzaamheid"],
  },
  {
    id: 4,
    naam: "Gemeente Edam-Volendam – Team Samenleving",
    beschrijving:
      "Werkt samen met inwoners en maatschappelijke organisaties aan een gezonde, veilige en inclusieve gemeente. Het team richt zich op onderwerpen als zorg, welzijn, jeugd, participatie, sport, cultuur en leefbaarheid. Valpreventie valt hier ook onder.",
    levensgebieden: ["Zorg & Welzijn", "Gezondheid & Sport"],
    adres: "W. van der Knoopdreef 1, 1132 KN Volendam",
    telefoon: "0299 398 398",
    email: null,
    website: "https://www.edam-volendam.nl/aangepastsporten",
    tags: ["samenleving", "welzijn", "zorg", "jeugd", "ouderen", "gezondheid", "sport", "cultuur", "onderwijs", "participatie", "inclusie", "leefbaarheid", "mantelzorg", "vrijwilligers", "maatschappelijke ondersteuning", "preventie", "samenwerking", "inwoners", "valpreventie"],
  },
  {
    id: 5,
    naam: "Gemeente Edam-Volendam – Schuldhulpverlening",
    beschrijving:
      "Schuldhulpverlening ondersteunt inwoners met geldzorgen of schulden. Samen wordt gekeken naar de financiële situatie en welke hulp het beste past. Dit kan bestaan uit advies, budgetbegeleiding, het treffen van betalingsregelingen, schuldbemiddeling of een schuldregeling. Het doel is om weer grip te krijgen op de financiën en problematische schulden te voorkomen of op te lossen.",
    levensgebieden: ["Financiën & Schulden"],
    adres: "W. van der Knoopdreef 1, 1132 KN Volendam",
    telefoon: "0299 398 398",
    email: null,
    website: "https://www.edam-volendam.nl/hulp-bij-geldzaken-en-schuld",
    tags: ["schuldhulpverlening", "schulden", "geldzaken", "financiën", "financiële ondersteuning", "budgetbegeleiding", "betalingsproblemen", "geldzorgen", "administratie", "hulp bij geldzaken", "schulden voorkomen", "schuldregeling", "inwoners", "zelfredzaamheid"],
  },
  {
    id: 6,
    naam: "Gemeente Edam-Volendam – Team Werk & Inkomen",
    beschrijving:
      "Ondersteunt inwoners met vragen over werk, uitkeringen, re-integratie en participatie. Biedt begeleiding naar werk en informatie over inkomensregelingen.",
    levensgebieden: ["Werk & Inkomen"],
    adres: "W. van der Knoopdreef 1, 1132 KN Volendam",
    telefoon: "0299 398 398",
    email: null,
    website: null,
    tags: ["werk", "inkomen", "uitkeringen", "jobcoach", "begeleiding", "informatie", "inkomensregelingen", "re-integratie", "participatie"],
  },
  {
    id: 7,
    naam: "Gemeente Edam-Volendam – Team Inburgering",
    beschrijving:
      "Team Inburgering ondersteunt nieuwkomers bij het inburgeringsproces. Het team helpt bij het opstellen van een persoonlijk inburgeringsplan, begeleidt tijdens het traject en biedt ondersteuning op het gebied van taal, participatie, werk, opleiding en zelfredzaamheid. Het doel is dat inwoners zo zelfstandig mogelijk kunnen meedoen in de samenleving.",
    levensgebieden: ["Inburgering & Participatie"],
    adres: "W. van der Knoopdreef 1, 1132 KN Volendam",
    telefoon: "0299 398 398",
    email: null,
    website: null,
    tags: ["inburgering", "nieuwkomers", "vluchtelingen", "statushouders", "integratie", "participatie", "Nederlandse taal", "taallessen", "maatschappelijke begeleiding", "werk", "opleiding", "zelfredzaamheid", "participatieverklaring", "ondersteuning", "begeleiding"],
  },
  {
    id: 8,
    naam: "Gemeente Edam-Volendam – Team Veiligheid (Wijkagenten)",
    beschrijving:
      "De wijkagenten zijn het vaste aanspreekpunt van de politie in de wijk. Zij werken samen met inwoners, ondernemers, de gemeente en maatschappelijke organisaties aan een veilige en leefbare omgeving. De wijkagenten signaleren problemen, helpen bij het voorkomen van overlast en criminaliteit en zijn benaderbaar voor vragen, meldingen en advies.",
    levensgebieden: ["Veiligheid"],
    adres: null,
    telefoon: null,
    email: "r.coster@edamvolendam.nl",
    website: null,
    tags: ["veiligheid", "wijkagent", "politie", "overlast", "criminaliteit", "leefbaarheid", "meldingen"],
  },
  {
    id: 9,
    naam: "Vluchtelingenwerk",
    beschrijving: "Ondersteunt vluchtelingen van aankomst naar toekomst.",
    levensgebieden: ["Inburgering & Participatie"],
    adres: "Dijkgraaf Poschlaan 8, 1135 GP Edam",
    telefoon: "085 334 2431",
    email: null,
    website: "https://www.vluchtelingenwerk.nl/",
    tags: ["vluchtelingen", "statushouders", "asielzoekers", "nieuwkomers", "inburgering", "integratie", "taal", "Nederlandse taal", "taalondersteuning", "participatie", "maatschappelijke begeleiding", "maatschappelijke ondersteuning", "begeleiding", "vrijwilligers", "spreekuur", "formulierenhulp", "administratie", "financiën", "werk", "opleiding", "onderwijs", "participatieverklaring", "gezinshereniging", "wonen", "gezondheidszorg", "opvoeding", "zelfredzaamheid", "sociale contacten", "welzijn", "juridische ondersteuning", "verblijfsvergunning"],
  },
  {
    id: 10,
    naam: "Sportkoepel",
    beschrijving:
      "Sportprogramma's gericht op lichamelijke fitheid en het versterken van je mentale veerkracht en het opbouwen van sociale connecties. Voor kinderen, volwassenen en ouderen.",
    levensgebieden: ["Gezondheid & Sport"],
    adres: "Heideweg 4, 1132 DB Volendam",
    telefoon: "0299 324 650",
    email: null,
    website: "https://sport-koepel.nl/",
    tags: ["sport", "gezondheid", "activiteiten", "senioren", "jeugd", "kinderen", "volwassenen", "cognitief", "fitness", "mentale veerkracht", "sociale connecties"],
  },
  {
    id: 11,
    naam: "Club en Buurthuiswerk Edam-Volendam (CBW)",
    beschrijving:
      "Een maatschappelijke organisatie die inwoners verbindt door het organiseren van activiteiten, het ondersteunen van vrijwilligers en het stimuleren van ontmoeting, participatie en persoonlijke ontwikkeling.",
    levensgebieden: ["Ontmoeting & Sociaal", "Jeugd & Gezin"],
    adres: "W.J. Tuijnstraat 15, 1131 ZH Volendam",
    telefoon: "0299 363 328",
    email: null,
    website: "https://cbwedamvolendam.nl/",
    tags: ["kinderopvang", "peuterspeelzalen", "kinderwerk", "tiener- en jongerenwerk", "seniorenwerk", "aandachtgroepen", "cursussen en clubs", "kunst en cultuur", "ontmoeting", "activiteiten", "vrijwilligers", "buurtactiviteiten", "sociaal contact", "taal", "taalcafé", "anderstaligen", "senioren", "ouderen", "bewegen", "creatieve activiteiten", "schilderen", "keramiek", "samen eten", "koken", "welzijn", "participatie", "daginvulling"],
  },
  {
    id: 12,
    naam: "Centrum Onafhankelijke Cliëntondersteuning (OCO)",
    beschrijving:
      "Beantwoordt vragen over zorg vanuit de Wet Langdurige Zorg (Wlz), de Wet Maatschappelijke Ondersteuning en de Jeugdwet. Helpt bij vragen over passende zorg thuis of in een zorginstelling en vragen die over wonen, zorg, hulpmiddelen, school, daginvulling en financiën gaan.",
    levensgebieden: ["Zorg & Welzijn"],
    adres: null,
    telefoon: "085 016 24 20",
    email: null,
    website: "https://www.centrumoco.nl/",
    tags: ["Wlz", "Wmo", "passende zorg", "wonen", "zorg", "hulpmiddelen", "ondersteuning", "onafhankelijk", "gratis", "financiën", "cliëntondersteuning"],
  },
  {
    id: 13,
    naam: "Dovida",
    beschrijving:
      "Een landelijke thuiszorgorganisatie die ouderen ondersteunt om zo lang mogelijk veilig, zelfstandig en comfortabel thuis te blijven wonen. De organisatie biedt onder meer huishoudelijke hulp, persoonlijke verzorging, begeleiding en mantelzorgondersteuning, met nadruk op persoonlijke aandacht en een vaste zorgverlener.",
    levensgebieden: ["Ouderenzorg", "Zorg & Welzijn"],
    adres: "Cruquiusweg 1, 2102 LS Heemstede",
    telefoon: "023 820 0912",
    email: null,
    website: "https://dovida.nl/",
    tags: ["thuiszorg", "zelfstandig", "langer thuis", "daginvulling", "huishoudelijke hulp", "mantelzorg", "begeleiding", "verzorging"],
  },
  {
    id: 14,
    naam: "Wooncompagnie",
    beschrijving:
      "Een woningcorporatie die betaalbare sociale huurwoningen aanbiedt en zich inzet voor voldoende woonaanbod, leefbare buurten en een prettig thuis voor haar huurders in Noord-Holland.",
    levensgebieden: ["Wonen"],
    adres: "Geldelozeweg 41, 1625 NW Hoorn",
    telefoon: "088 171 8190",
    email: null,
    website: "https://www.wooncompagnie.nl/",
    tags: ["wonen", "bewoners", "huren", "Edam", "Zeevang", "sociale huurwoning", "woningcorporatie"],
  },
  {
    id: 15,
    naam: "De Vooruitgang",
    beschrijving:
      "Een woningcorporatie in Volendam die betaalbare sociale huurwoningen aanbiedt en zich inzet voor prettig wonen, leefbare buurten en goede dienstverlening aan haar huurders.",
    levensgebieden: ["Wonen"],
    adres: "Julianaweg 190, 1131 DL Volendam",
    telefoon: "0299 399 960",
    email: null,
    website: "https://www.devooruitgang.com/",
    tags: ["wonen", "bewoners", "huren", "Volendam", "sociale huurwoning", "woningcorporatie"],
  },
  {
    id: 16,
    naam: "Bibliotheek Waterland",
    beschrijving: "Bibliotheek met activiteitenaanbod op het gebied van taal en jeugd.",
    levensgebieden: ["Ontmoeting & Sociaal", "Jeugd & Gezin"],
    adres: "Dijkgraaf Poschlaan 8, 1135 GP Edam",
    telefoon: "0299 250 500",
    email: null,
    website: "https://www.bibliotheekwaterland.nl/",
    tags: ["taalles", "buurtambassadeurs", "taalgroep", "jeugd", "lezen", "voorlezen", "taal"],
  },
  {
    id: 17,
    naam: "De Zorgcirkel",
    beschrijving:
      "Zorgorganisatie die ondersteuning biedt aan ouderen, waaronder thuiszorg, wijkverpleging, wonen met zorg en revalidatie.",
    levensgebieden: ["Ouderenzorg", "Zorg & Welzijn"],
    adres: "Verschillende locaties door de hele gemeente",
    telefoon: "088 559 9500",
    email: null,
    website: "https://zorgcirkel.nl/",
    tags: ["senioren", "ouderen", "mantelzorgers", "dementie", "casemanagement dementie", "thuiszorg", "wijkverpleging", "verpleging", "verzorging", "persoonlijke verzorging", "verpleeghuiszorg", "ouderenzorg", "langdurige zorg", "Wlz", "eerstelijnsverblijf", "revalidatiezorg", "palliatieve zorg", "dagbesteding", "behandeling", "zorgadvies", "mantelzorgondersteuning", "verpleeghuis", "woonzorgcentrum", "wonen met zorg", "kleinschalig wonen", "tijdelijk verblijf", "respijtzorg", "zelfstandig thuis wonen", "langer thuis wonen", "geheugenproblemen", "chronische aandoening", "lichamelijke beperking", "gezondheid", "welzijn", "ontmoeting", "activiteiten", "sociale contacten", "Edam-Volendam", "Waterland"],
  },
  {
    id: 18,
    naam: "Evean",
    beschrijving:
      "Zorgorganisatie die ondersteuning biedt aan mensen thuis en in woonzorglocaties, met onder andere wijkverpleging en huishoudelijke hulp.",
    levensgebieden: ["Ouderenzorg", "Zorg & Welzijn"],
    adres: "Heideweg 1B, 1132 DA Volendam",
    telefoon: "0900 9897",
    email: null,
    website: "https://www.evean.nl/",
    tags: ["ouderenzorg", "thuiszorg", "wijkverpleging", "verpleging", "verzorging", "persoonlijke verzorging", "verpleeghuiszorg", "revalidatiezorg", "geriatrische revalidatie", "eerstelijnsverblijf", "palliatieve zorg", "hospicezorg", "dementiezorg", "casemanagement dementie", "dagbesteding", "specialistische zorg", "behandeling", "ergotherapie", "fysiotherapie", "logopedie", "diëtetiek", "psychologische zorg", "mantelzorgondersteuning", "welzijn", "activiteiten", "wonen met zorg", "verpleeghuis", "woonzorgcentrum", "kleinschalig wonen", "tijdelijk verblijf", "respijtzorg", "zelfstandig thuis wonen", "langer thuis wonen", "ouderen", "senioren", "mantelzorgers", "chronische aandoening", "geheugenproblemen", "gezondheid", "Edam-Volendam", "Zaanstreek-Waterland"],
  },
  {
    id: 19,
    naam: "Vitaal Waterland",
    beschrijving:
      "Draagt bij aan een gezonde, vitale en gelukkige leefstijl van alle inwoners in de gemeente. Dit door het stimuleren en samenbrengen van kennis en ervaring van lokale partijen. Verbindt lokale initiatieven aan (nieuw) beleid.",
    levensgebieden: ["Gezondheid & Sport"],
    adres: null,
    telefoon: null,
    email: "dianne@vitaalwaterland.nl",
    website: null,
    tags: ["leefstijl", "gezondheid", "preventie", "lokale initiatieven", "beleid", "vitaliteit"],
  },
  {
    id: 20,
    naam: "GGD Zaanstreek-Waterland",
    beschrijving:
      "Gemeentelijke gezondheidsdienst die zich richt op het bevorderen van gezondheid en preventie. Biedt onder andere gezondheidsadvies, infectiebestrijding en ondersteuning bij publieke gezondheid.",
    levensgebieden: ["Gezondheid & Sport"],
    adres: "Vurehout 2, 1507 EC Zaandam",
    telefoon: "0900 254 54 54",
    email: "psilven@ggdzw.nl",
    website: "https://www.ggdzw.nl",
    tags: ["gezondheid", "preventie", "gezondheidsadvies", "infectiebestrijding", "publieke gezondheid", "GGD"],
  },
  {
    id: 21,
    naam: "Kinderpraktijk Melany",
    beschrijving:
      "Kinderpraktijk Melany biedt begeleiding aan kinderen en jongeren van 4 tot en met 18 jaar met sociale, emotionele en gedragsvragen. De praktijk biedt individuele therapie, gezinsbegeleiding, sociale vaardigheidstrainingen (SOVA) en ondersteuning aan ouders.",
    levensgebieden: ["Jeugd & Gezin"],
    adres: "Pegasusstraat 16, 1131 NB Volendam",
    telefoon: "06 51278117",
    email: null,
    website: "https://kinderpraktijkmelany.nl/",
    tags: ["kinderen", "jeugd", "jongeren", "ouders", "gezin", "opvoeding", "opvoedondersteuning", "gedrag", "emoties", "sociale vaardigheden", "SOVA", "weerbaarheid", "begeleiding", "therapie", "gezinsbegeleiding", "ontwikkeling", "mentale gezondheid"],
  },
  {
    id: 22,
    naam: "Moedige Moeders",
    beschrijving: "Steun voor naasten van verslaafden.",
    levensgebieden: ["Verslavingszorg"],
    adres: "Jaap Zwarthoedstraat 6, 1132 HS Volendam",
    telefoon: null,
    email: null,
    website: "https://www.moedigemoeders.nl/",
    tags: ["nazorg", "praatgroep", "verslaving", "drugs", "ouders", "broers", "zussen", "middelengebruik", "preventie", "ouderbijeenkomsten"],
  },
  {
    id: 23,
    naam: "Hulpgroep Geven en Nemen",
    beschrijving:
      "Ondersteunt mensen of gezinnen die het financieel moeilijk hebben en helpt hen op weg.",
    levensgebieden: ["Financiën & Schulden"],
    adres: "Kerkepad 1, 1131 XN Volendam",
    telefoon: null,
    email: null,
    website: "https://hulpgroepgevenennemenpci.nl/",
    tags: ["vrijwilligers", "hulpvraag", "hulpaanbod", "burenhulp", "mantelzorg", "ontmoeting", "sociale contacten", "buurt", "ondersteuning", "samenredzaamheid", "welzijn", "inwoners", "Edam-Volendam", "financieel"],
  },
  {
    id: 24,
    naam: "Bij Ootje",
    beschrijving:
      "Ontmoetingsplek voor jong en oud, waar generaties elkaar ontmoeten, samenwerken en van elkaar leren. Verbinding, ontwikkeling en inclusie staan centraal.",
    levensgebieden: ["Ontmoeting & Sociaal"],
    adres: "Friese Vlaak 1, 1132 MP Volendam",
    telefoon: "+31 299 746 023",
    email: null,
    website: "https://bij-ootje.nl/",
    tags: ["ontmoeting", "jong en oud", "senioren", "ouderen", "vrijwilligers", "participatie", "dagbesteding", "leerwerkplek", "Alzheimer café", "verbinding", "inclusie"],
  },
  {
    id: 25,
    naam: "Humanitas Thuisadministratie",
    beschrijving:
      "Humanitas helpt met praktische hulp, tips, vriendschappelijk contact en een luisterend oor.",
    levensgebieden: ["Financiën & Schulden"],
    adres: "p/a Annie van Eesstraat 2, 1507 SH Zaanstad",
    telefoon: "06 22 54 01 87",
    email: null,
    website: "https://www.humanitas.nl/zawa/",
    tags: ["thuisadministratie", "administratie", "geldzaken", "financiën", "ondersteuning", "vrijwilligers", "hulp bij administratie", "formulierenhulp", "financiële zelfredzaamheid", "schuldenpreventie", "thuisbegeleiding"],
  },
  {
    id: 26,
    naam: "Over Rood",
    beschrijving:
      "Een vrijwilligersorganisatie die ondernemers met schulden en achterstanden helpt om de boel weer op orde te krijgen.",
    levensgebieden: ["Financiën & Schulden"],
    adres: "Chris Lebeaustraat 4, Amsterdam",
    telefoon: "085 040 8412",
    email: null,
    website: "https://overrood.nl/",
    tags: ["ondernemers", "zzp'ers", "administratie", "financiën", "geldzaken", "schulden", "financiële ondersteuning", "coaching", "begeleiding", "hulp bij administratie", "financiële zelfredzaamheid", "ondernemersadvies"],
  },
  {
    id: 27,
    naam: "NewBees",
    beschrijving: "Inburgering en participatie voor en door nieuwkomers. Met name in Purmerend.",
    levensgebieden: ["Inburgering & Participatie"],
    adres: "Waterlandlaan 52, 1441 MP Purmerend",
    telefoon: "+31 6 47127873",
    email: null,
    website: "https://new-bees.org/",
    contactpersoon: "Rouba Saada (coördinator)",
    tags: ["nieuwkomers", "vluchtelingen", "statushouders", "integratie", "participatie", "vrijwilligerswerk", "sociale contacten", "taal", "Nederlandse taal", "meedoen", "werk", "netwerk", "begeleiding", "zelfredzaamheid"],
  },
  {
    id: 28,
    naam: "Brijder Verslavingszorg",
    beschrijving: "Verslavingszorg.",
    levensgebieden: ["Verslavingszorg", "GGZ & Psychische Hulp"],
    adres: "Waterlandplein 1, Purmerend",
    telefoon: "088 358 3710",
    email: null,
    website: "https://brijder.nl/w/purmerend",
    tags: ["verslavingszorg", "verslaving", "alcohol", "drugs", "middelengebruik", "preventie", "behandeling", "begeleiding", "herstel", "jongeren", "volwassenen", "psychische ondersteuning", "ambulante hulp", "GGZ"],
  },
  {
    id: 29,
    naam: "Indigo",
    beschrijving: "Mentale ondersteuning.",
    levensgebieden: ["GGZ & Psychische Hulp"],
    adres: "Oude Parklaan 127, 1901 ZZ Castricum",
    telefoon: "088 357 1100",
    email: null,
    website: "https://indigo.nl/",
    tags: ["GGZ", "psychische hulp", "mentale gezondheid", "begeleiding", "behandeling", "angst", "depressie", "stress", "burn-out", "preventie", "kortdurende behandeling", "volwassenen", "jongeren"],
  },
  {
    id: 30,
    naam: "Parnassia",
    beschrijving: "Voor mensen met ernstige psychische problemen.",
    levensgebieden: ["GGZ & Psychische Hulp"],
    adres: "Oude Parklaan 125, 1901 ZZ Castricum",
    telefoon: "088 358 01 00",
    email: null,
    website: "https://parnassia.nl/",
    tags: ["GGZ", "geestelijke gezondheidszorg", "psychische klachten", "psychiatrie", "behandeling", "begeleiding", "volwassenen", "jongeren", "herstel", "ambulante hulp", "verslavingszorg", "mentale gezondheid"],
  },
  {
    id: 31,
    naam: "De Prinsenstichting",
    beschrijving: "Zorg en ondersteuning aan mensen met een verstandelijke beperking.",
    levensgebieden: ["Zorg & Welzijn"],
    adres: "Kwadijkerpark 8, 1444 JE Purmerend",
    telefoon: "088 356 00 10",
    email: null,
    website: "https://www.prinsenstichting.nl/",
    tags: ["verstandelijke beperking", "gehandicaptenzorg", "begeleiding", "wonen met zorg", "dagbesteding", "ondersteuning", "participatie", "zelfstandigheid", "cliënten", "zorg aan huis"],
  },
  {
    id: 32,
    naam: "Odion",
    beschrijving: "Beschermde woonlocaties voor mensen met een fysieke of verstandelijke beperking.",
    levensgebieden: ["Zorg & Welzijn", "Wonen"],
    adres: "Mercuriusweg 5A, 1531 AD Wormer",
    telefoon: "0299 412 812",
    email: null,
    website: "https://odion.nl/",
    tags: ["verstandelijke beperking", "gehandicaptenzorg", "begeleiding", "wonen met zorg", "24-uurszorg", "dagbesteding", "ambulante begeleiding", "persoonlijke verzorging", "ondersteuning", "zelfstandigheid", "participatie", "dementie", "Boelenspark", "Helena Smitstraat", "Jan Platstraat", "Brederodestraat", "Henegouwen", "Maria Goretti"],
  },
  {
    id: 33,
    naam: "HZW Huisartsenzorg",
    beschrijving:
      "HZW vertegenwoordigt de huisartsen uit Zaanstreek en Waterland. Onder andere door nascholing en bijeenkomsten.",
    levensgebieden: ["Gezondheid & Sport"],
    adres: "Mercuriusweg 5, 1531 AD Wormer",
    telefoon: "075 201 0221",
    email: null,
    website: "https://hzwhuisartsenzorg.nl/",
    tags: ["huisartsenzorg", "huisartsen", "Zaanstreek", "Waterland", "nascholing"],
  },
  {
    id: 34,
    naam: "Maison Thuiszorg",
    beschrijving: "Voorziet in zorgvraag rondom huishoudelijk werk.",
    levensgebieden: ["Zorg & Welzijn"],
    adres: "Zaanweg 99, 1521 DP Wormerveer",
    telefoon: "075 615 1447",
    email: null,
    website: "https://maisonthuiszorg.nl/contact/",
    tags: ["thuiszorg", "wijkverpleging", "persoonlijke verzorging", "verpleging", "zorg aan huis", "ouderen", "ondersteuning thuis", "huishoudelijke ondersteuning", "begeleiding", "zelfredzaamheid", "langer thuis wonen", "mantelzorg"],
  },
  {
    id: 35,
    naam: "Centrum voor Jeugd en Gezin (CJG)",
    beschrijving:
      "Voor ouders, opvoeders, kinderen en jongeren tot 23 jaar met vragen over opgroeien, opvoeden, gezondheid en ontwikkeling. Aanspreekpunt voor informatie, advies, ondersteuning en preventieve jeugdhulp. Samen met verschillende professionals en organisaties biedt het CJG passende ondersteuning, zodat kinderen en jongeren gezond en veilig kunnen opgroeien.",
    levensgebieden: ["Jeugd & Gezin"],
    adres: "Wieringenlaan 1a, 1132 MJ Volendam",
    telefoon: "0299 748 004",
    email: null,
    website: "https://cjgedamvolendam.nl/",
    tags: ["jeugd", "jongeren", "kinderen", "ouders", "opvoeding", "opvoedondersteuning", "opgroeien", "jeugdgezondheid", "ontwikkeling", "preventie", "advies", "begeleiding", "gezin", "ouderschap", "jeugdhulp", "cursussen"],
  },
  {
    id: 36,
    naam: "De Toegang Edam-Volendam",
    beschrijving:
      "De Toegang Edam-Volendam is het centrale aanspreekpunt voor inwoners met vragen over zorg, welzijn, opvoeding, werk, inkomen en ondersteuning. Samen wordt gekeken naar passende oplossingen en de ondersteuning die nodig is om zelfstandig en actief mee te kunnen doen in de samenleving.",
    levensgebieden: ["Zorg & Welzijn", "Jeugd & Gezin", "Werk & Inkomen"],
    adres: "Langemeerstraat 14, 1135 JE Edam",
    telefoon: "0299 391 507",
    email: null,
    website: "https://www.toegang-edam-volendam.nl/",
    tags: ["zorg", "welzijn", "ondersteuning", "Wmo", "jeugd", "opvoeding", "werk", "inkomen", "hulpvragen", "begeleiding", "advies", "toegang tot zorg", "maatschappelijke ondersteuning", "inwoners", "zelfredzaamheid", "participatie", "jongerenwerk", "jongerencoaching"],
  },
  {
    id: 37,
    naam: "Levvel",
    beschrijving:
      "Onderdeel van de Toegang. Schoolmaatschappelijk werk, gedragswetenschappers en jeugdmaatschappelijk werk.",
    levensgebieden: ["Jeugd & Gezin"],
    adres: null,
    telefoon: "088 054 70 00",
    email: null,
    website: "https://www.levvel.nl/",
    tags: ["kinderen", "jongeren", "gezinnen", "opvoeding", "opvoedondersteuning", "schoolmaatschappelijk werk", "jeugdmaatschappelijk werk", "school", "onderwijs", "begeleiding"],
  },
  {
    id: 38,
    naam: "Mee Dichtbij",
    beschrijving: "(Ambulante) ondersteuning voor mensen, jeugdigen en gezinnen met een beperking.",
    levensgebieden: ["Zorg & Welzijn", "Jeugd & Gezin"],
    adres: null,
    telefoon: "020 512 7272",
    email: null,
    website: "https://meedichtbij.nl/",
    tags: ["cliëntondersteuning", "onafhankelijke cliëntondersteuning", "begeleiding", "ondersteuning", "LVB", "licht verstandelijke beperking", "autisme", "NAH", "niet-aangeboren hersenletsel", "lichamelijke beperking", "chronische ziekte", "psychische kwetsbaarheid", "gezin", "kinderen", "jongeren", "zorg aanvragen", "voorzieningen", "dagbesteding", "wonen", "werk", "onderwijs", "participatie", "zelfredzaamheid", "sociale contacten", "vervoer"],
  },
  {
    id: 39,
    naam: "Praktijk Thuis en School",
    beschrijving: "Psychologische hulp voor kinderen, jeugdigen en hun ouders. Laagdrempelig en kortdurend.",
    levensgebieden: ["Jeugd & Gezin"],
    adres: "Volendam",
    telefoon: "0299 794 004",
    email: null,
    website: "https://praktijkthuisenschool.nl/",
    tags: ["kinderen", "jongeren", "jeugd", "ouders", "gezin", "opvoeding", "opvoedondersteuning", "begeleiding", "school", "onderwijs", "leerproblemen", "ontwikkeling", "gedrag", "sociale vaardigheden", "coaching", "remedial teaching", "ondersteuning thuis", "ondersteuning op school"],
  },
  {
    id: 40,
    naam: "Energiek Zeedam",
    beschrijving:
      "Lokale energiecoöperatie die inwoners ondersteunt en informeert over duurzame energie. Richt zich op het samen verduurzamen van de leefomgeving.",
    levensgebieden: ["Duurzaamheid & Energie"],
    adres: null,
    telefoon: null,
    email: null,
    website: "https://energiekzeedam.nl/",
    tags: ["duurzaamheid", "energie", "energiebesparing", "energieadvies", "verduurzaming", "isolatie", "zonnepanelen", "bewonersinitiatief", "vrijwilligers", "informatie", "bewustwording", "energiearmoede"],
  },
  {
    id: 41,
    naam: "Het Juridisch Loket",
    beschrijving:
      "Organisatie die gratis juridisch advies en informatie biedt aan inwoners over uiteenlopende juridische vragen.",
    levensgebieden: ["Juridisch"],
    adres: "Bibliotheek Waterland, Waterlandlaan 40, Purmerend",
    telefoon: "0800 8020",
    email: null,
    website: "https://www.juridischloket.nl/",
    tags: ["juridisch advies", "rechtshulp", "juridische vragen", "gratis advies", "inkomen", "wonen", "werk", "ontslag", "schulden", "contracten", "bezwaar en beroep", "formulierenhulp", "ondersteuning", "gratis"],
  },
  {
    id: 42,
    naam: "Scheiden met Floris",
    beschrijving:
      "Organisatie die ondersteuning biedt bij scheidingen, met begeleiding en advies rondom scheidingsproces, communicatie en juridische zaken.",
    levensgebieden: ["Juridisch", "Jeugd & Gezin"],
    adres: "Damcoogh 63, 1132 EB Volendam",
    telefoon: "+31 6 51920457",
    email: null,
    website: "https://www.scheidenmetfloris.nl/",
    tags: ["scheiden", "echtscheiding", "mediation", "familierecht", "ouderschapsplan", "alimentatie", "begeleiding", "juridische ondersteuning", "relatiebreuk", "gezin", "kinderen", "afspraken maken"],
  },
  {
    id: 43,
    naam: "Scheidingsplein",
    beschrijving: "Platform dat ondersteuning biedt aan mensen die gaan scheiden of gescheiden zijn.",
    levensgebieden: ["Juridisch", "Jeugd & Gezin"],
    adres: null,
    telefoon: "085 073 33 00",
    email: null,
    website: "https://scheidingsplein.nl/",
    tags: ["scheiden", "echtscheiding", "mediation", "familierecht", "ouderschapsplan", "alimentatie", "juridische ondersteuning", "begeleiding", "kinderen", "gezin", "relatiebreuk", "afspraken maken", "hulp bij scheiden"],
  },
  {
    id: 44,
    naam: "Bewegen Werkt",
    beschrijving:
      "Organisatie die mensen ondersteunt bij het ontwikkelen van een actieve gezonde leefstijl. Biedt programma's en begeleiding op het gebied van participatie en het vergroten van zelfredzaamheid.",
    levensgebieden: ["Gezondheid & Sport", "Werk & Inkomen"],
    adres: "1441 MP Purmerend",
    telefoon: null,
    email: null,
    website: "https://www.bewegenwerkt.nl/",
    tags: ["bewegen", "sport", "gezondheid", "vitaliteit", "leefstijl", "ouderen", "senioren", "anderstaligen", "volwassenen", "lichamelijke activiteit", "conditie", "welzijn", "sociale contacten", "ontmoeting", "participatie", "preventie", "gezonde leefstijl", "inburgeren"],
  },
  {
    id: 45,
    naam: "De Fixbrigade",
    beschrijving:
      "Organisatie die inwoners helpt met energiebesparende maatregelen in huis. Gericht op het verlagen van woonlasten.",
    levensgebieden: ["Duurzaamheid & Energie", "Wonen"],
    adres: null,
    telefoon: null,
    email: null,
    website: "https://fixbrigade.nl/",
    tags: ["energiebesparing", "energiearmoede", "duurzaamheid", "energiebesparende maatregelen", "woningverbetering", "isolatie", "energieadvies", "energiekosten", "inwoners", "hulp aan huis", "vrijwilligers"],
  },
  {
    id: 46,
    naam: "Duurzaam Edam-Volendam",
    beschrijving:
      "Initiatief gericht op het ondersteunen en informeren van inwoners over duurzaamheid, energiebesparing en verduurzamen van woningen. Stimuleert bewoners om bewust om te gaan met energie.",
    levensgebieden: ["Duurzaamheid & Energie"],
    adres: null,
    telefoon: null,
    email: null,
    website: "https://duurzaamedamvolendam.nl/",
    tags: ["energiebesparing", "energiearmoede", "duurzaamheid", "energiebesparende maatregelen", "woningverbetering", "isolatie", "energieadvies", "energiekosten", "inwoners", "hulp aan huis", "vrijwilligers"],
  },
  {
    id: 47,
    naam: "Bewindvoering Chantal Commandeur",
    beschrijving:
      "Organisatie die ondersteuning biedt bij financieel beheer en beschermingsbewind voor mensen die tijdelijk of langdurig niet in staat zijn hun financiën zelfstandig te regelen.",
    levensgebieden: ["Financiën & Schulden"],
    adres: "Postbus 1098, 1700 BB Heerhugowaard",
    telefoon: "06 30686747",
    email: null,
    website: "https://cc-bewindvoering.nl/",
    tags: ["bewindvoering", "financiële ondersteuning", "geldzaken", "financiën", "administratie", "budgetbeheer", "schulden", "schuldenpreventie", "inkomensbeheer", "beschermingsbewind", "financiële zelfredzaamheid"],
  },
  {
    id: 48,
    naam: "123 Moos",
    beschrijving:
      "Zorgorganisatie die ambulante gespecialiseerde begeleiding biedt aan mensen met complexe problematiek, zoals verslavingsproblematiek, psychische klachten en multiproblematiek. Daarnaast ondersteuning gericht op herstel, maatschappelijke participatie en re-integratie naar werk of dagbesteding.",
    levensgebieden: ["GGZ & Psychische Hulp", "Verslavingszorg", "Werk & Inkomen"],
    adres: "Nijverheidsweg 3, 1442 LD Purmerend",
    telefoon: "+31 (0)20 235 1100",
    email: null,
    website: "https://123moos.nl/",
    tags: ["jongeren", "jeugd", "jongerenwerk", "coaching", "begeleiding", "preventie", "middelengebruik", "drugs", "alcohol", "verslaving", "weerbaarheid", "sociale vaardigheden", "mentale gezondheid", "persoonlijke ontwikkeling", "talentontwikkeling", "zelfvertrouwen", "welzijn", "activiteiten", "participatie", "ondersteuning", "multiproblematiek", "re-integratie"],
  },
  {
    id: 49,
    naam: "Visio",
    beschrijving:
      "Ondersteunt kinderen en volwassenen met een visuele beperking. Inwoners van Edam-Volendam kunnen terecht voor advies, revalidatie, begeleiding, hulpmiddelen en training om zo zelfstandig mogelijk te kunnen wonen, leren, werken en deelnemen aan de samenleving.",
    levensgebieden: ["Zorg & Welzijn"],
    adres: null,
    telefoon: null,
    email: null,
    website: null,
    tags: ["slechtziendheid", "blindheid", "visuele beperking", "oogzorg", "begeleiding", "revalidatie", "hulpmiddelen", "training", "zelfstandigheid"],
  },
  {
    id: 50,
    naam: "Belastingdienst",
    beschrijving: "Overheidsorganisatie voor vragen over belastingen en toeslagen.",
    levensgebieden: ["Financiën & Schulden"],
    adres: null,
    telefoon: null,
    email: "maatschappelijkdienstverleners@belastingdienst.nl",
    website: null,
    tags: ["belastingen", "toeslagen", "financiën", "overheid"],
  },
  {
    id: 51,
    naam: "60+ Bus Edam-Volendam",
    beschrijving: "Seniorenvervoer in Edam en Volendam.",
    levensgebieden: ["Vervoer", "Ouderenzorg"],
    adres: "Jan Platstraat 83, 1132 HE Volendam",
    telefoon: "06 16429987",
    email: null,
    website: "https://60plusbusedamvolendam.nl/",
    tags: ["vervoer", "senioren", "vrijwilligers", "kleine ritten", "boodschappenhulp", "kleine vergoeding"],
  },
  {
    id: 52,
    naam: "KoMee",
    beschrijving:
      "Specialistische jeugdhulp aan kinderen, jongeren en gezinnen. Cultuursensitieve, gezinsgerichte en oplossingsgerichte aanpak bij opvoed- en opgroeivragen.",
    levensgebieden: ["Jeugd & Gezin"],
    adres: null,
    telefoon: "085 0600 663",
    email: null,
    website: "https://komee.nl/",
    tags: ["jeugdhulp", "jeugd", "jongeren", "kinderen", "gezinnen", "opvoeding", "begeleiding", "ontwikkeling", "specialistische jeugdhulp", "gezinsondersteuning", "mentale gezondheid", "cultuursensitief"],
  },
  {
    id: 53,
    naam: "Fysiotherapie Duin",
    beschrijving:
      "Fysiotherapiepraktijk en gezondheidscentrum die ondersteuning biedt bij klachten, herstel na blessures en operaties, revalidatie en het verbeteren van de lichamelijke gezondheid.",
    levensgebieden: ["Gezondheid & Sport"],
    adres: "Schoolstraat 17, 1131 CK Volendam",
    telefoon: "0299 366 086",
    email: null,
    website: "https://www.duinplus.nl/",
    tags: ["fysiotherapie", "gezondheidscentrum", "bewegen", "vitaliteit", "revalidatie", "blessures", "lichamelijke gezondheid"],
  },
  {
    id: 54,
    naam: "Fysiotherapie Kernpraktijken",
    beschrijving:
      "Samenwerkingsverband van fysiotherapiepraktijken in de regio Zaanstreek-Waterland. Biedt fysiotherapeutische behandelingen gericht op het herstellen, verbeteren en behouden van de lichamelijke gezondheid, bewegen en functioneren.",
    levensgebieden: ["Gezondheid & Sport"],
    adres: "Papaverstraat 27, 1131 HK Volendam",
    telefoon: "0299 32 01 75",
    email: null,
    website: "https://www.kernpraktijken.nl/",
    tags: ["fysiotherapie", "gezondheidscentrum", "bewegen", "vitaliteit", "revalidatie", "lichamelijke gezondheid"],
  },
  {
    id: 55,
    naam: "Fysiotherapie Kirchhoff",
    beschrijving:
      "Fysiotherapiepraktijk en gezondheidscentrum die ondersteuning biedt bij klachten, herstel na blessures en operaties, revalidatie en het verbeteren van de lichamelijke gezondheid.",
    levensgebieden: ["Gezondheid & Sport"],
    adres: "Volendam",
    telefoon: null,
    email: null,
    website: "https://www.kirchhoff-fysio.nl/",
    tags: ["fysiotherapie", "gezondheidscentrum", "bewegen", "vitaliteit", "revalidatie"],
  },
  {
    id: 56,
    naam: "VerhuisMe",
    beschrijving: "VerhuisMe is gespecialiseerd in verhuizingen, transport en ladderverhuur.",
    levensgebieden: ["Vervoer"],
    adres: "Kwadijk 166, 1471 CK Kwadijk",
    telefoon: "06 24242708",
    email: null,
    website: "https://verhuisme.nl/",
    tags: ["verhuizen", "transport", "verhuur"],
  },
  {
    id: 57,
    naam: "Tzorg",
    beschrijving:
      "Zorgorganisatie die ondersteuning biedt bij het zelfstandig thuis wonen, met name via huishoudelijke hulp en individuele begeleiding vanuit de Wmo. Helpt inwoners bij het behouden van een schoon en leefbaar huis en het vergroten van zelfredzaamheid.",
    levensgebieden: ["Zorg & Welzijn"],
    adres: null,
    telefoon: null,
    email: null,
    website: "https://www.tzorg.nl/",
    tags: ["huishoudelijke hulp", "thuiszorg", "ondersteuning thuis", "huishoudelijke ondersteuning", "ouderen", "inwoners", "zelfredzaamheid", "langer thuis wonen"],
  },
  {
    id: 58,
    naam: "BOV (Buurtwacht Organisatie Volendam)",
    beschrijving:
      "Een professionele buurtwacht die zich inzet voor een veilige en leefbare omgeving in Volendam. Vrijwilligers houden toezicht, signaleren situaties, werken samen met veiligheidsdiensten en zijn een zichtbaar aanspreekpunt voor inwoners en bezoekers.",
    levensgebieden: ["Veiligheid"],
    adres: null,
    telefoon: "+31 6 24916562",
    email: null,
    website: "https://bov-24.nl/",
    tags: ["buurtwacht", "vrijwilligers", "toezicht", "signaleren", "signalen", "veiligheid", "aanspreekpunt", "bewoners", "jongeren", "vuurwerk", "kermis"],
  },
  {
    id: 59,
    naam: "Buurtkamer Singelwijk",
    beschrijving:
      "Een ontmoetingsplek voor bewoners van de Singelwijk. Jong en oud kunnen er terecht voor een kop koffie, een praatje en verschillende activiteiten. De buurtkamer stimuleert ontmoeting, verbinding en bewonersinitiatieven en biedt ruimte voor onder andere een Taalcafé en buurtactiviteiten.",
    levensgebieden: ["Ontmoeting & Sociaal"],
    adres: "Langemeerstraat 14A, 1135 JE Edam",
    telefoon: "06 26282477",
    email: null,
    contactpersoon: "Quinty (buurtverbinder)",
    website: "https://www.facebook.com/people/SingelwijkEdam/61574326114242/",
    tags: ["ontmoeting", "buurtkamer", "bewoners", "sociale contacten", "wijkactiviteiten", "Taalcafé", "vrijwilligers", "verbinding", "leefbaarheid", "participatie", "Singelwijk", "Edam"],
  },
  {
    id: 60,
    naam: "Jeugdagent (Politie)",
    beschrijving:
      "De jeugdagent richt zich specifiek op kinderen en jongeren. Door aanwezig te zijn op straat, op scholen en bij verenigingen signaleert de jeugdagent vroegtijdig problemen en helpt overlast te voorkomen. De jeugdagent werkt nauw samen met ouders, jongerenwerk, scholen, hulpverlening en de gemeente en is een aanspreekpunt voor vragen of zorgen over jeugd.",
    levensgebieden: ["Veiligheid", "Jeugd & Gezin"],
    adres: null,
    telefoon: null,
    email: "addis.riet@politie.nl",
    website: null,
    tags: ["jeugdagent", "veiligheid", "jongeren", "kinderen", "politie", "school", "overlast", "preventie"],
  },
  {
    id: 61,
    naam: "Wijksteunpunt",
    beschrijving:
      "Het Wijksteunpunt is een laagdrempelig aanspreekpunt voor alle inwoners van de gemeente Edam-Volendam. Inwoners kunnen er terecht met vragen over zorg, welzijn, geldzaken, wonen, mantelzorg, vrijwilligerswerk, eenzaamheid en andere maatschappelijke onderwerpen. De sociaal werkers bieden informatie, advies, ondersteuning en verwijzen waar nodig door naar passende hulp. Ook is het Wijksteunpunt een plek voor ontmoeting en samenwerking met vrijwilligers en maatschappelijke organisaties.",
    levensgebieden: ["Zorg & Welzijn", "Ontmoeting & Sociaal"],
    adres: "Dijkgraaf Poschlaan 8, 1135 GP Edam",
    telefoon: "0299 391 507",
    email: null,
    website: "https://www.civic-edam-volendam.nl",
    tags: ["sociaal werk", "welzijn", "ondersteuning", "advies", "ontmoeting", "buurt", "wijk", "inwoners", "zorg", "mantelzorg", "vrijwilligers", "eenzaamheid", "sociale contacten", "participatie", "activiteiten", "hulpvragen", "doorverwijzing", "zelfredzaamheid", "welzijnswerk", "geldzaken", "wonen"],
  },
  {
    id: 62,
    naam: "EdamVolendamVoorElkaar",
    beschrijving:
      "Brengt inwoners, vrijwilligers en organisaties met elkaar in contact. Via het platform kunnen inwoners hulp vragen, hulp aanbieden of vrijwilligerswerk vinden. Het stimuleert ontmoeting, betrokkenheid en samenredzaamheid binnen de gemeente.",
    levensgebieden: ["Ontmoeting & Sociaal"],
    adres: null,
    telefoon: null,
    email: null,
    website: "https://edamvolendamvoorelkaar.nl",
    tags: ["vrijwilligerswerk", "vrijwilligers", "hulpvraag", "hulpaanbod", "burenhulp", "inwoners", "ontmoeting", "sociale contacten", "samenredzaamheid", "participatie", "maatschappelijke betrokkenheid", "ondersteuning", "buurt", "vrijwilligersorganisaties"],
  },
  {
    id: 63,
    naam: "Casemanagers Dementie (De Zorgcirkel)",
    beschrijving: "Casemanagers dementie van De Zorgcirkel.",
    levensgebieden: ["Ouderenzorg"],
    adres: "Door de hele gemeente",
    telefoon: null,
    email: null,
    contactpersonen: [
      { naam: "Simone van 't Hoff", telefoon: "06 50081214" },
      { naam: "Bjorn Hekke", telefoon: "06 30512076" },
    ],
    website: "https://zorgcirkel.nl/zorg-thuis/zorg-en-ondersteuning-thuis/casemanager-dementie/",
    tags: ["dementie", "casemanagement", "ouderen", "senioren", "geheugenproblemen", "begeleiding"],
  },
  {
    id: 64,
    naam: "Wijkverpleegkundigen (De Zorgcirkel)",
    beschrijving: "Wijkverpleegkundigen van De Zorgcirkel.",
    levensgebieden: ["Ouderenzorg", "Gezondheid & Sport"],
    adres: "Meerdere locaties in Volendam",
    telefoon: "06 1465 9324",
    email: null,
    website: "https://zorgcirkel.nl/zorg-thuis/zorg-en-ondersteuning-thuis/thuiszorg-wijkverpleging/",
    tags: ["wijkverpleging", "verpleging", "thuiszorg", "gezondheid"],
  },
  {
    id: 65,
    naam: "Activiteiten CBW (Senioren en Volwassenen)",
    beschrijving: "Activiteitenoverzicht van Club en Buurthuiswerk voor senioren en volwassenen.",
    levensgebieden: ["Ontmoeting & Sociaal"],
    adres: "Friese Vlaak, Volendam",
    telefoon: null,
    email: null,
    contactpersonen: [
      { naam: "Marieke Keizer", telefoon: "06 12242087" },
      { naam: "Jane Snoek", telefoon: "06 21892903" },
      { naam: "Celeste Veerman", telefoon: "06 29147320" },
    ],
    website: "https://cbwedamvolendam.nl/activiteiten-cursussen/",
    tags: ["ontmoeting", "activiteiten", "cursussen", "workshops", "vrijwilligers", "buurtactiviteiten", "sociaal contact", "sociale contacten", "taal", "taalcafé", "anderstaligen", "senioren", "ouderen", "bewegen", "creatieve activiteiten", "kunst en cultuur", "schilderen", "keramiek", "samen eten", "koken", "welzijn", "participatie", "daginvulling"],
  },
  {
    id: 66,
    naam: "Dorpsraden",
    beschrijving: "Dorpsraden verspreid over de gemeente.",
    levensgebieden: ["Ontmoeting & Sociaal"],
    adres: "Door de hele gemeente",
    telefoon: null,
    email: null,
    contactpersonen: [
      { naam: "Hans Visser (Hobrede)", telefoon: "06 15542420" },
      { naam: "Ed Willms (Hobrede)", telefoon: "06 51534944" },
      { naam: "Roel en Samantha (Etersheim, Molen de Breek)", telefoon: "06 21420990" },
      { naam: "Ted Landaal (Oosthuizen)", telefoon: "06 10138886" },
      { naam: "Jan Willem Tellegen (Schardam)", telefoon: "06 53437600" },
      { naam: "Dirk Olsthoorn (Beets)", telefoon: "06 18181756" },
      { naam: "Susan Rietveld (Kerk Kwadijk)", telefoon: "06 13106262" },
      { naam: "Jaap Oostveen (Kerk Middelie)", telefoon: "06 51159403" },
      { naam: "Agatha Mol (Volendam/Edam)", telefoon: "06 28911929" },
      { naam: "Afra Hellingman (Warder)", telefoon: "06 83668124" },
      { naam: "Pauline Silven (Volendam)", telefoon: "06 30953466" },
      { naam: "Agatha van den Hogen (Volendam)", telefoon: "06 29044023" },
      { naam: "Monique Chervet (Volendam/Edam/Kernen)", telefoon: "06 28410524" },
      { naam: "Margriet Visser (Edam/Ye)", telefoon: "06 11052767" },
      { naam: "Hedy van Leeuwen (Volendam/Edam)", telefoon: "06 38379733" },
    ],
    website: null,
    tags: ["ontmoeting", "ontwikkeling", "dorpsraad", "bewoners", "buurt", "leefbaarheid"],
  },
  {
    id: 67,
    naam: "Sleutelfiguren",
    beschrijving: "Sleutelfiguren in de gemeente.",
    levensgebieden: ["Ontmoeting & Sociaal"],
    adres: null,
    telefoon: null,
    email: null,
    website: null,
    tags: ["sleutelfiguren", "vrijwilligers", "buurt", "signalering"],
  },
  {
    id: 68,
    naam: "Zicht op Geld",
    beschrijving: "Financieel adviseur voor senioren.",
    levensgebieden: ["Financiën & Schulden", "Ouderenzorg"],
    adres: "Door de hele gemeente",
    telefoon: null,
    email: null,
    contactpersoon: "Lyda Rijlaarsdam (06 83829414)",
    website: "https://www.zichtopgeld.nl",
    tags: ["financiële regelzaken", "verpleeghuis opname", "senioren", "financieel advies"],
  },
  {
    id: 69,
    naam: "Maaltijdservice Uitgekookt",
    beschrijving: "Maaltijdservice: gezonde maaltijden aan huis. Verse maaltijden bezorgd aan huis.",
    levensgebieden: ["Zorg & Welzijn"],
    adres: "Door de hele gemeente",
    telefoon: "085 040 6065",
    email: null,
    website: "https://uitgekookt.nl",
    tags: ["maaltijdservice", "gezonde maaltijden", "bezorging", "thuiswonend", "ouderen"],
  },
  {
    id: 70,
    naam: "SVB (Sociale Verzekeringsbank)",
    beschrijving: "Dubbele kinderbijslag aanvragen bij intensieve zorg.",
    levensgebieden: ["Financiën & Schulden", "Jeugd & Gezin"],
    adres: null,
    telefoon: null,
    email: null,
    website: "https://www.svb.nl/nl/kinderbijslag/dubbele-kinderbijslag",
    tags: ["dubbele kinderbijslag", "intensieve zorg", "kinderbijslag", "financiën"],
  },
  {
    id: 71,
    naam: "Welzijn Wonen Plus",
    beschrijving:
      "Servicepunt Edam-Volendam waar enthousiaste vrijwilligers werken. Abonnees kunnen praktische diensten en persoonlijke ondersteuning aanvragen.",
    levensgebieden: ["Zorg & Welzijn", "Ontmoeting & Sociaal"],
    adres: "Door de hele gemeente",
    telefoon: "0299 323 101",
    email: null,
    website: "https://www.welzijnwonenplus.nl/edam-volendam",
    tags: ["vrijwilligers", "diensten", "praktische hulp", "persoonlijke ondersteuning", "senioren"],
  },
  {
    id: 72,
    naam: "Huishoudelijke Hulp Particulier",
    beschrijving: "Particuliere huishoudelijke hulp.",
    levensgebieden: ["Zorg & Welzijn"],
    adres: "Door de hele gemeente",
    telefoon: "088 430 3091",
    email: null,
    website: "https://ikzoekeenwittewerkster.nl",
    tags: ["particuliere huishoudelijke hulp", "schoonmaak", "huishoudelijk"],
  },
  {
    id: 73,
    naam: "Activiteiten voor Senioren 2025",
    beschrijving: "Overzicht van activiteiten voor senioren in 2025.",
    levensgebieden: ["Ontmoeting & Sociaal", "Ouderenzorg"],
    adres: "Door de hele gemeente",
    telefoon: null,
    email: null,
    website: null,
    tags: ["activiteiten", "senioren", "cultuur", "kunst", "beweging", "creatief", "sport", "gezondheid", "eten", "samenzijn", "ontmoeting"],
  },
  {
    id: 74,
    naam: "Vrijwillige Tolk",
    beschrijving: "Ondersteuning bij bewoners met tolken.",
    levensgebieden: ["Inburgering & Participatie"],
    adres: "Door de hele gemeente",
    telefoon: null,
    email: null,
    contactpersoon: "Neran Nasser (06 44750850)",
    website: null,
    tags: ["tolken", "taal", "ondersteuning", "nieuwkomers", "anderstaligen"],
  },
  {
    id: 75,
    naam: "Maaltijden Beets",
    beschrijving: "Maaltijden voor een lage prijs om samen te eten in Beets.",
    levensgebieden: ["Ontmoeting & Sociaal"],
    adres: "Beets",
    telefoon: null,
    email: null,
    contactpersoon: "Sonja Kelderman (06 30520495)",
    website: null,
    tags: ["maaltijden", "samen eten", "Beets", "ontmoeting", "lage prijs"],
  },
  {
    id: 76,
    naam: "JOGG-regisseur",
    beschrijving:
      "De spil in de lokale aanpak voor een gezondere leefomgeving voor kinderen en jongeren (JOGG: Gezonde Jeugd, Gezonde Toekomst).",
    levensgebieden: ["Gezondheid & Sport", "Jeugd & Gezin"],
    adres: null,
    telefoon: "06 20432627",
    email: null,
    website: null,
    tags: ["gezondheid", "jeugd", "kinderen", "jongeren", "gezonde leefomgeving", "preventie", "JOGG"],
  },
  {
    id: 77,
    naam: "Centraal Zorgverlener",
    beschrijving: "Betrokken bij gezinnen met kinderen met obesitas.",
    levensgebieden: ["Gezondheid & Sport", "Jeugd & Gezin"],
    adres: null,
    telefoon: null,
    email: "psilven@ggdzw.nl",
    website: null,
    tags: ["gezondheid", "obesitas", "kinderen", "gezinnen", "gezond eten", "sport", "beweging"],
  },
  {
    id: 78,
    naam: "LEF (Programma Gemeente Edam-Volendam)",
    beschrijving:
      "De gemeente Edam-Volendam is begonnen met de ontwikkeling van het programma LEF. De basis van LEF is het zoeken naar het antwoord op de vraag hoe we met z'n allen ervoor kunnen zorgen dat het gezonde verstand gaat zegevieren als het gaat om het maken van keuzes. Voor het verhogen van de betrokkenheid van ouders richt LEF zich op vier domeinen: gezin, school, peergroep en vrije tijd.",
    levensgebieden: ["Jeugd & Gezin", "Gezondheid & Sport"],
    adres: null,
    telefoon: null,
    email: "m.dofferhoffveerman@edamvolendam.nl",
    website: "https://lef-edamvolendam.nl/",
    tags: ["jeugd", "jongeren", "kinderen", "preventie", "middelengebruik", "alcohol", "drugs", "vapen", "gezonde leefstijl", "mentale gezondheid", "weerbaarheid", "ouderbetrokkenheid", "opvoeding", "opvoedondersteuning", "bewustwording", "activiteiten", "vrijetijdsbesteding", "sport", "sociale omgeving", "samenwerking", "veiligheid"],
  },
  {
    id: 79,
    naam: "Respijtzorg Het Buitenhuis",
    beschrijving: "Het Buitenhuis is een plek voor mantelzorgers en voor de mensen die zij zorg verlenen.",
    levensgebieden: ["Zorg & Welzijn", "Ouderenzorg"],
    adres: "Noorderweg 104, 1456 NK Weidewormer",
    telefoon: "088 559 9777",
    email: null,
    website: "https://www.zorgcirkel.nl/het-buitenhuis",
    tags: ["logeren", "weekje weg", "dagje uit", "sporten en spel", "tuinclub", "mantelzorg", "respijtzorg", "ontlasting"],
  },
  {
    id: 80,
    naam: "De Luisterlijn",
    beschrijving: "Zijn er 24/7 voor een luisterend oor. Is er voor iedereen.",
    levensgebieden: ["GGZ & Psychische Hulp", "Zorg & Welzijn"],
    adres: null,
    telefoon: "088 076 7000",
    email: null,
    website: "https://www.deluisterlijn.nl/",
    tags: ["luisterend oor", "praatje", "eenzaamheid", "24/7", "anoniem", "mentale ondersteuning"],
  },
  {
    id: 81,
    naam: "De Mantelzorglijn",
    beschrijving:
      "Voor al je vragen over mantelzorg. Bereikbaar van maandag t/m donderdag van 09:00 tot 17:00 en vrijdag van 09:00 tot 13:00.",
    levensgebieden: ["Zorg & Welzijn"],
    adres: null,
    telefoon: "030 760 6055",
    whatsapp: "06 27236854",
    email: null,
    website: null,
    tags: ["mantelzorg", "advies", "luisterend oor", "ondersteuning", "mantelzorgers"],
  },
  {
    id: 82,
    naam: "Het Alzheimer Café",
    beschrijving: "Is een plek om lotgenoten te ontmoeten, elke tweede donderdag van de maand van 14:30 tot 16:30.",
    levensgebieden: ["Ouderenzorg", "Ontmoeting & Sociaal"],
    adres: "Bij Ootje, Friese Vlaak 1, 1132 MP Volendam",
    telefoon: "+31 299 746 023",
    email: null,
    website: "https://www.alzheimer-nederland.nl/alzheimer-cafe",
    tags: ["mensen met dementie", "naasten", "ontmoeting", "lotgenoten", "Alzheimer"],
  },
  {
    id: 83,
    naam: "Ontmoetingscentrum Meerwijk (De Zorgcirkel)",
    beschrijving:
      "Biedt dagbesteding aan mensen met dementie die nog thuis wonen. In een veilige en huiselijke omgeving kunnen bezoekers deelnemen aan activiteiten die zijn afgestemd op hun interesses en mogelijkheden. Het doel is om zelfstandigheid, sociale contacten en welzijn te behouden, terwijl mantelzorgers tijdelijk worden ontlast. Het ontmoetingscentrum biedt persoonlijke begeleiding, structuur en een zinvolle daginvulling. Aanmelding verloopt via het Bemiddelingsbureau of een casemanager dementie.",
    levensgebieden: ["Ouderenzorg"],
    adres: "Dijkgraaf Poschlaan 8, Edam",
    telefoon: null,
    email: null,
    website: null,
    tags: ["dagbesteding", "dementie", "ontmoeting", "mantelzorg", "respijtzorg", "activiteiten", "begeleiding"],
  },
  {
    id: 84,
    naam: "Huisvesting (Overzicht)",
    beschrijving: "Overzicht van huisvestingsmogelijkheden.",
    levensgebieden: ["Wonen"],
    adres: null,
    telefoon: null,
    email: null,
    websites: [
      "https://www.flexwonennh.nl/locaties/",
      "https://www.pararius.nl",
      "https://www.woningnet.nl",
      "https://www.rentbird.nl",
      "https://www.woonmatchwaterland.nl",
      "https://www.funda.nl",
    ],
    tags: ["wonen", "huisvesting", "huren", "urgentie", "sociale huurwoning", "vrije sector"],
  },
  {
    id: 85,
    naam: "Huisvesting Urgentie",
    beschrijving: "Urgentiebeoordeling door beleidsmedewerker wonen.",
    levensgebieden: ["Wonen"],
    adres: "W. van der Knoopdreef 1, 1132 KN Volendam",
    telefoon: null,
    email: null,
    contactpersoon: "A. Khabbazha (06 13749151)",
    website: null,
    tags: ["huisvesting", "urgentie", "wonen", "huren", "beleidsadviseur"],
  },
]
